### ISSUE TITLE
Unable to correctly deserialize strings containing null characters

### ISSUE THREAD

**Issue by dkonigsberg** [protobuf-c/protobuf-c#203]
The protocol buffer string type can contain a UTF-8 string, which can contain null bytes as characters. Due to the use of null-terminated C strings in this library, it is impossible to completely deserialize those strings.

This does not cause problems in other protocol buffer libraries written for languages that use data/length string objects, which leads to interoperability issues.

There should be a way to handle this case, either by providing a separate length parameter for strings, via a command-line argument that generates serializer code for strings similar to the "bytes" type, or some other method.

**Comment by edmonds** [comment]
Hi, Derek:

It's my understanding that the only code point that can be encoded with a `\0` byte in UTF-8 is `U+0000`. Does this really cause an interoperability issue? Genuinely asking -- I don't do much work with UTF-8 data. Do you have any examples of applications that use the `U+0000` character in protobuf `string` fields and fail to interoperate with `protobuf-c`?

The protobuf developer guide is very brief on this topic, only noting that "A string must always contain UTF-8 encoded or 7-bit ASCII text" and "`string` and `bytes` are compatible as long as the bytes are valid UTF-8." It doesn't say "UTF-8, except for `U+0000`", so I guess you're right; representing a protobuf `string` as a C `char *` in `protobuf-c` was a mistake.

Researching the issue, I see there's something called "Modified UTF-8" where `U+0000` is encoded as the byte sequence `"\xC0\x80"`. If the `protobuf-c` decoder guaranteed that `U+0000` would always be transcoded to that byte sequence and `\0` would only occur at the end of the string, would that solve your problem? But I worry that it would introduce overhead scanning and replacing `\0` bytes, rather than just copying the bytes.

I can see introducing a command-line option for `protoc-c` that forces the code generator to make a protobuf `string` field use `ProtobufCBinaryData` rather than `char *`. As long as it doesn't break the library ABI (and I don't think it does, as this would be equivalent to editing the `.proto` file and replacing `string` with `bytes`), it's suitable for a `protobuf-c` 1.x release.

**Comment by dkonigsberg** [comment]
I actually discovered this issue in the field. A serialized protocol buffer created by the official Java version of the library was encoding strings that contained null characters, as Java has no problems handling this case. However, these strings came through as truncated when decoding them with `libprotobuf-c`.

Upon further investigation, I learned two things:

1. The `string` and `bytes` types are serialized identically, and thus interchangeable
2. The official C++ library represents both types as `std::string` (which is sufficiently equivalent to `ProtobufCBinaryData` in that it has a data pointer and a length field)

I agree that the documentation seems somewhat vague on this issue. However, since this case can happen, it is important to preserve interoperability. I think that adding the command line option would be the best solution at this point.
