### ISSUE TITLE
String assignment

### ISSUE THREAD

**Issue by acsdkquery** [protobuf-c/protobuf-c#293]

**Comment by acsdkquery** [comment]
Is it possible to assign a string that has lots of tabs(\t) and new lines(\n) and white spaces( ), when I tried to assign the same and pack a buffer and unpacked it, it throwing errors.

**Comment by Thomas-Lerman** [comment]
I realize this issue is 1-1/2 years old, but I am trying to even find how to properly do a string assignment. I wish the examples were not "to do". I hope this issue is still being monitors. Thank you in advance,

**Comment by robert-alfaro** [comment]
something like this?

proto:
```
message foo {
  string name = 1;
}
```

c code:
```
// somewhere you have a string
char str[32] = "hello";
...
// init your message variable
// assign string
msg.name = (char *)str;
// get packed size
// pack message
...
```

**Comment by Thomas-Lerman** [comment]
Thank you for the reply. I was thinking that might be the case. I could be wrong on some of the following (it has been several months since looking at this):

1. The trick seems to be that the "str" variable should not go out of scope if "msg.name" is used elsewhere.
2. When unpacking, it seems that memory is allocated for a null-terminated string.

The difference, if this is the case, could cause some issues for me. I am trying to support old binary data as well as the new protobuf with the same code. In other words, take binary data and convert it to an unpacked protobuf. Then use the unpacked protobuf to access the data.

If I am understanding and remembering correctly, maybe what I need to do is take the old binary, convert it to an unpacked protobuf, pack it, and then unpack it into a member variable that can be used. It seems like this would allow the free_unpacked() to do_free() without issue. Comments?

**Comment by robert-alfaro** [comment]
Glad you replied and this didn't just end up a reply into a black hole.. I too had some recent issues with string assignment, specifically inside a oneof, so I thought I'd help.

1. Correct since the proto msg string is a pointer and str in the example is a stack variable. You could use a global, static, or dynamically allocate space for the var.

2. I am using a char that im not null terminating, it seems to work fine.

I'm currently using a pointer to a message that I allocate mem and use the struct for state tracking..write some data in it...read somewhere else. That way I don't sorry about scope. I don't think you need to pack and unpack to use the msg data. Be sure any fields you assign that have a `has_` field paired with it also get set.

**Comment by Thomas-Lerman** [comment]
On 2, my binary data actually has an allocated number of bytes, which may or may not be null-terminated.

In my case, I currently never write to the binary data and it should be the same when I get the protobuf. The data is really status coming from an external source. Well, technically, I currently memcpy to the buffer when I receive a new status.

Although all of my fields are marked optional, I have not seen the has_ methods yet, but it seems like it was something about my configuration (arguments). I definitely want to be able to use these at some time to be able to do things a bit differently.

**Comment by robert-alfaro** [comment]
Ah, are you using proto2? I am using proto 3...not sure the implementation difference for string handling. Have you tried using bytes type? The data in proto msg would not be a pointer but rather an array encapsulated in the message. (Now I need to go double check that.)

**Comment by Thomas-Lerman** [comment]
Proto3. I have not tried the bytes type. Of course, the wiki here indicates "to do" just like strings. I may have to check it out, do research, etc.

**Comment by robert-alfaro** [comment]
I know the feeling of wanting to use the string type.. but often dealing with the bytes straight up is the way to go.  Is your data arbitrary our string literals.  Treat the data as bytes (uint8_t) with a pointer and length.  Thankfully c strings are units of char... a byte.

**Comment by lipnitsk** [comment]
I believe the issue will be addressed when an option is added to support generating ProtobufCBinaryData for string members (#203)
