### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by definename** [protobuf-c/protobuf-c#301]
I'm using protoc.exe with plugin protoc-gen-c.exe in order to generate C structures in this way:

```
protoc.exe --plugin=D:\Test\Gen\protoc-gen-c.exe --proto_path=D:\Test\TestProto D:\Test\TestProto\Test.proto --c_out=D:\Test\TestProto\Test
```
I invoke command line from folder where protoc.exe is located

But have following error:
```
D:\Test>protoc.exe --plugin=D:\Test\Gen\protoc-gen-c.exe --proto_path=D:\Test\TestProto D:\Test\TestProto\Test.proto --c_out=D:\Test\TestProto\Test
[libprotobuf WARNING D:\install\libs\protobuf\protobuf_samples\build\vc14-x86-release\protobuf-prefix\src\protobuf\src\google\protobuf\compiler\parser.cc:546] No syntax specified for the proto file: Test.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
--c_out: protoc-gen-c: The system cannot find the file specified.
```

I am absolutely sure is that all paths is correct, which file is missing?

protoc.exe **version 3.1.0**
protoc-gen-c.exe **version 1.3.0**

**Comment by stevenroose** [comment]
I have the same with the Dart plugin. The executable `protoc-gen-dart` is in my path and I can execute it manually. I also restarted the console. 

Still, I get `--dart_out: protoc-gen-dart: The system cannot find the file specified.`

Temporarily on Windows, sad to see that it doesn't work here.

**Comment by rhelenagh** [comment]
Me too Stevenroose any progress?

**Comment by definename** [comment]
I did not solve this issue.

**Comment by rhelenagh** [comment]
Hi @definename 

This tip I got from Neville Dipale and for me it worked!
`protoc -Iproto proto/[file].proto --plugin=protoc-gen-dart=c:\Users\[youruser]\AppData\Roaming\Pub\Cache\bin\protoc-gen-dart.bat --dart_out=grpc:lib/generated`

I hope it works for you too
Best

**Comment by rhelenagh** [comment]
@definename 
Oh sorry my solution works with the plugin for Dart, and I see that you want to generate for C. I have not used C, anyway these options are for other languages maybe you can guide:
**for golang**
`protoc -I=. --go_out=plugins=grpc:..\go\src\messages .\messages.proto`

**for c#**
`protoc -I=. --csharp_out ..\c#\Messages --grpc_out  ..\c#\Messages .\messages.proto --plugin=protoc-gen-grpc=C:\Users\[youruser]\.nuget\packages\grpc.tools\1.10.0\tools\windows_x64\grpc_csharp_plugin.exe`

**Comment by dovholuk** [comment]
I had the same problem - using procmon it seems that protoc is scanning various locations... For example:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\Hostx86\x86\protoc-gen-c.*	NO SUCH FILE	Filter: protoc-gen-c.*
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\vcpackages\protoc-gen-c.*	NO SUCH FILE	Filter: protoc-gen-c.*
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\protoc-gen-c.*	NO SUCH FILE	Filter: protoc-gen-c.*
`
it's not a great answer but putting your protoc-gen-c.exe into one of these folders should make it work for you... For me I chose `D:\Windows Kits\10\bin\x86` because I had specifically built x86 libraries.

**Comment by dovholuk** [comment]
GAH - actually it's even easier. the format is --plugin=NAME=PATH... so the easiest and best answer is just:
protoc.exe --plugin=protoc-gen-c=V:\path\to\protoc-gen-c.exe --c_out=. source.proto
