### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by sanjayku** [protobuf-c/protobuf-c#312]
There were new changes in https://github.com/google/protobuf.git. Because of that protobuf-c install is getting failed. Error faced as below:

checking google/protobuf/compiler/command_line_interface.h usability... no
checking google/protobuf/compiler/command_line_interface.h presence... no
checking for google/protobuf/compiler/command_line_interface.h... no
ERROR: Installing protobuf-c library. Please check env_protobuf.log

**Comment by austinglaser** [comment]
I'm also experiencing this issue. I'm attaching `config.log` in the hopes that it'll help
[config.log](https://github.com/protobuf-c/protobuf-c/files/1843087/config.log)

**Comment by haggaie** [comment]
I saw in the config log that recent versions of this header file require C++11.

**Comment by hasan4791** [comment]
Have u installed protobuf and if you had did u install using --prefix=/usr or default installation. Kindly check for the env variable PKG_CONFIG_PATH...
if protobuf is installed in /usr, then PKG_CONFIG_PATH=/usr/lib/pkgconfig
If its installed in /usr/local then PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

This helped me to get rid of this particular error.

**Comment by haggaie** [comment]
I installed protobuf using `./configure --prefix=/usr --libdir=/usr/lib64`. I'm using CentOS and I believe this matches its directory structure. I worked around the issue by downgrading protobuf to an older version where the `command_line_interface.h` header file didn't require C++11.

**Comment by austinglaser** [comment]
I tried installing `protobuf` with no prefix, as well uninstalling it and
reinstalling with `--prefix=/usr`. Both produced the same error.

My `PKG_CONFIG_PATH` is empty, and I'm on ubuntu 16.04. However,
`pkg-config --cflags protobuf` correctly has `-I/usr/local/include`
 (or `-I/usr/include`, depending on the prefix I'd used).

It's worth noting that I was able to successfully install the package when
I installed protobuf from the `v3.4.1` tag rather than from the most recent
master, suggesting that some change between those two points is responsible
for the error.

Austin Glaser
Embedded Engineer
Boulder Engineering Studio, LLC
-----------------------------------
glaser@boulderes.com
(303) 834-1091 x733
www.BoulderES.com <http://www.boulderes.com/>
-------------------------------
3297 Walnut St.
Boulder CO 80301

DISCLAIMER
Privileged/Confidential information may be contained in this message and
any related attachments. If you are not the addressee indicated in this
message (or responsible for delivery of the message to such person), you
may not copy, review, distribute or forward the contents of this message to
anyone. In such case, you should notify the sender by reply e-mail and
delete this message from your computer.

**Comment by austinglaser** [comment]
It's also worth noting that when installing both from `master` and `v3.4.1`, the file in question exists (with the default prefix, it's at `/usr/local/include/google/protobuf/compiler/command_line_interface.h`)

> I saw in the config log that recent versions of this header file require C++11.

@haggaie Looking at the log more closely, it looks like you're right. Probably the build just needs to be configured to use c++11?

**Comment by sympthom** [comment]
I have tried to install protobuf-c (and protobuf before) on two different distributions and still get:

checking google/protobuf/compiler/command_line_interface.h usability... no
checking google/protobuf/compiler/command_line_interface.h presence... no
checking for google/protobuf/compiler/command_line_interface.h... no
configure: error: required protobuf header file not found

Is there a solution to this?

**Comment by sanjayku** [comment]
Hi Martin,

There are some changes in protobuf or protobuf-c made and it was not
building together.
Can you jump back in the git source of both protobuf and protobuf-c to date
around last November-December. It should work then.

-

*With Best Regards,*

Sanjay Kumar

VVDN Technologies Pvt Ltd

*Cell : *+91 7401549158 | *Skype :* sanjay.vvdn

**Comment by morris2600** [comment]
@edmonds ,  did this issue fixed in 1.3.1 or not yet?   
I experiencing  this in latest protobuf-c

**Comment by lyphknoten** [comment]
Is this going to be fixed some time?

**Comment by nanfengnan1** [comment]
it's so puzzling? Isn't protobuf-c a separate project? Why does it have to rely on the protbuf project's header files?
