### ISSUE TITLE
Built-in generator --c_out specifies a maximum edition PROTO3 which is not the protoc maximum 2023.

### ISSUE THREAD

**Issue by oliverkurth** [protobuf-c/protobuf-c#716]
I am getting the weird error message `Built-in generator --c_out specifies a maximum edition PROTO3 which is not the protoc maximum 2023.` in a github workflow, running `macos-latest`. `protobuf-c` version is `1.5.0_4`, installed with homebrew. See the workflow run here: https://github.com/oliverkurth/rhizofs/actions/runs/8777926044/job/24083596389?pr=23
```
Run make
  
protoc-c --c_out=. src/proto/rhizofs.proto
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1713755397.8[4](https://github.com/oliverkurth/rhizofs/actions/runs/8777926044/job/24083596389?pr=23#step:4:4)3579   20617 command_line_interface.cc:153[4](https://github.com/oliverkurth/rhizofs/actions/runs/8777926044/job/24083596389?pr=23#step:4:5)] Built-in generator --c_out specifies a maximum edition PROTO3 which is not the protoc maximum 2023.
make: *** [src/proto/rhizofs.pb-c.h] Error 1
Error: Process completed with exit code 2.
```

You can see the file `rhizofs.proto` here: https://github.com/oliverkurth/rhizofs/blob/master/src/proto/rhizofs.proto

I tried adding `syntax = "proto2";` on top, but that had no effect.

This is working locally on MacOS 14.4, and I have version is `1.5.0_3`, also installed with homebrew. I have never seen this until now when I tried to create a workflow to test my project with MacOS.

**Comment by edmonds** [comment]
This is https://github.com/Homebrew/homebrew-core/issues/168501, related to the changes in the open PR https://github.com/protobuf-c/protobuf-c/pull/711. Apparently the homebrew maintainers decided to just apply the patches from that open PR in the homebrew version "1.5.0_4" of protobuf-c: https://github.com/Homebrew/homebrew-core/commit/7fa7f6ebf802117e101769819457f31f4e3741a4. (1.5.0 is the upstream protobuf-c version, 4 is the homebrew revision.)

If homebrew supports rolling back to a previous version of the protobuf-c package (I believe 1.5.0_3 should work) I would recommend doing that, but I'm not that familiar with the homebrew package manager and I don't know if that's possible.

Since this code hasn't been released and hasn't been merged to `next` (the branch where changes targeted at the next release of protobuf-c are prepared) and the problematic code only exists in an open PR, I'm going to close this issue. Feel free to comment on #711 or file an issue with homebrew. I'll link this issue into #711 so the report doesn't get lost.

Thanks!
